# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 903172ac285a4b9c0fd897c8971e9d0238bfe635217b554b958ff3a2265d3313e14573e880693147def5a73bfd38df832ec496b62e6dbc5151ed1de3480a367d

test:
  secret_key_base: cd90c13bb8eff02e4c46bc23a872e3066b17c692d39e0ad0c58fe204288486a429a785fbaadd9ad6c88e8ceb7e40861e828b70a5d1c9847e86b14ad3c1973f81

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
